---
- name: enable sensu-client to survive reboot
  service: name=sensu-client enabled=yes

- name: generate config files
  template:
    src={{ item }}.json.j2
    dest=/etc/sensu/conf.d/{{ item }}.json
    owner=sensu
    group=sensu
    mode=0640
    backup=yes
  with_items:
    client
    checks
  notify: restart sensu client