---
- name: add rabbitmq sensu vhost
  rabbitmq_vhost: name=/sensu state=present

- name: add rabbitmq sensu user and set priveleges
  rabbitmq_user:
    user={{ sensu_server_rabbitmq_user }}
    password={{ sensu_server_rabbitmq_password }}
    vhost=/sensu
    configure_priv=.*
    read_priv=.*
    write_priv=.*
    state=present

- name: add the key of the sensu official repo
  apt_key: url=https://repos.sensuapp.org/apt/pubkey.gpg state=present

- name: add the sensu official repo
  copy:
    src=sensu-server.list
    dest=/etc/apt/sources.list.d/
    backup=yes
  register: aptrepo

- name: refresh apt cache
  apt: update_cache=yes
  when: aptrepo.changed

- name: install sensu-server
  apt: name=sensu state=latest

- name: copy the patched init script
  copy:
    src=sensu-{{ item }}
    dest=/etc/init.d/
    owner=root
    group=root
    mode=755
    backup=yes
  with_items:
    - server
    - api

- name: ensure the patched init script are used
  command: /usr/sbin/update-rc.d sensu-{{ item }} remove && /usr/sbin/update-rc.d sensu-{{ item }} defaults
  with_items:
    - server
    - api

- name: Create ssl dir
  file:
    path=/etc/sensu/ssl
    owner=sensu
    group=sensu
    mode=0750
    state=directory

- name: Copy ssl files
  copy:
    src=files/sensu_{{ item }}.pem
    dest=/etc/sensu/ssl/{{ item }}.pem
    owner=sensu
    group=sensu
    mode=0640
    backup=yes
  with_items:
    - client_cert
    - client_key

- name: enable sensu-{server,api,dashboard} to survive reboot
  service: name=sensu-{{ item }} enabled=yes
  with_items:
    - server
    - api
    - dashboard

- name: copie config.json
  template:
    src=sensu.config.json.j2
    dest=/etc/sensu/config.json
    owner=sensu
    group=sensu
    mode=0640
    backup=yes
  notify: restart sensu server daemons

- name: generate /etc/sensu/conf.d/checks.json file
  template:
    src=checks.json.j2
    dest=/etc/sensu/conf.d/checks.json
    owner=sensu
    group=sensu
    mode=0750
  notify: restart sensu server daemons

- name: generate /etc/sensu/conf.d/handlers.json file
  template:
    src=handlers.json.j2
    dest=/etc/sensu/conf.d/handlers.json
    owner=sensu
    group=sensu
    mode=0750
  notify: restart sensu server daemons
